### ISSUE TITLE
graph_test.py does not contain any tests

### ISSUE THREAD

**Issue by sdbarker** [crvallance/iperf-graph#1]
**Issue Description**
The file `graph_test.py` does not contain any tests.  In fact, it seems as though you forgot to add the tests entirely.

**Steps to Reproduce**
View the contents of `graph_test.py`

**Expected**
`graph_test.py` contains tests.

**Actual**
`graph_test.py` contains no tests.

**Comment by crvallance** [comment]
Resolved in commit c50614fe3a67127dd79d19ed9916939e969ff6e1
