### ISSUE TITLE
Feature Request: Simpler filename masking

### ISSUE THREAD

**Issue by sdbarker** [crvallance/iperf-graph#3]
While the potential for infinite flexibility using the filename masking and delimiter concept could provide a lot of value, given that all ends of this process are controlled, it may be simpler to enforce a naming convention, and use that convention to generate KVPs that are used in an output format.  As an example, a filename format of `key1-value1_key2-value2`... could accept an output format using any of the bare keys, `key1 key2`.

Filename: `dist-30ft_mode-Client_band-five_device-S10.json`
Format: `dist mode`
Output: `30ft Client`

Example code:
```python
def key_parse(coded_name, fmt):
  elements = dict(kvp.split('-') for kvp in coded_name.split('_'))
  for key in elements:
    fmt = str.replace(fmt, key, elements[key])
  return fmt
```

**Comment by crvallance** [comment]
resolved with config file
